---
- name: Build the image with buildctl
  shell: |
    cd /code
    /usr/local/bin/buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=docker,name=djangoarticleapp:latest,dest=/tmp/djangoarticleapp.tar

- name: Load the image into containerd
  command: >
    ctr -n k8s.io images import /tmp/djangoarticleapp.tar

- name: Pull Postgres
  command: >
    ctr -n k8s.io images pull docker.io/library/postgres:latest

- name: Cleanup
  shell: |
    rm -rf /tmp/bin
    rm -rf /tmp/buildkit.tar.gz
    rm -rf /tmp/djangoarticleapp.tar
# - name: Rename image
#   command: > 
#     ctr -n k8 images tag docker.io/library/djangoarticleapp:latest djangoarticleapp:latest

# - name: Remove image
#   command: > 
#     ctr -n k8 images remove docker.io/library/djangoarticleapp:latest