- name: Configure gitlab secret and apply manifests
  hosts: master
  gather_facts: true
  become: true
  become_user: "{{ ansible_user }}"
  vars_files:
    - group_vars/all
  tasks:
    - name: Execute kube_apply_manifests yml
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: kube_create_gitlab_secret.yml
      when: hostvars[inventory_hostname].role == "primary"

    - name: Execute kube_apply_manifests yml
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: kube_apply_manifests.yml
      when: hostvars[inventory_hostname].role == "primary"
