---
- name: Get Node Port
  hosts: master
  gather_facts: true
  tasks:
    - name: Kube get node port yml
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: kube_get_node_port.yml
      when: hostvars[inventory_hostname].role == "primary"
