---
- name: Update Filebeat configuration with Elasticsearch password
  hosts: master
  gather_facts: false
  tasks:
    - name: Retrieve Elasticsearch password from Kubernetes secret
      ansible.builtin.shell: |
        set -o pipefail
        kubectl get secrets --namespace=logging elasticsearch-master-credentials -o jsonpath='{.data.password}' | base64 -d; echo
      register: secret_out
      changed_when: false
      when: hostvars[inventory_hostname].role == "primary"

    - name: Debug - Show retrieved password
      ansible.builtin.debug:
        msg: "The Elasticsearch password is: {{ secret_out }}"

    - name: Render django-deployment manifest with GitLab image
      ansible.builtin.template:
        src: "{{ lookup('env', 'CI_PROJECT_DIR') }}/provision/helm/elk/filebeat/values-filebeat.yml.j2"
        dest: "{{ lookup('env', 'CI_PROJECT_DIR') }}/provision/helm/elk/filebeat/values-filebeat.yml"
        mode: '0644'
      delegate_to: localhost
      vars:
        elastic_password: "{{ secret_out.stdout }}"
