- hosts: master
  gather_facts: yes  
  become: true
  become_user: "{{ ansible_user }}"
  vars_files:
    - group_vars/all
  tasks:
    - name: kube_apply_manifests yml
      include_role:
        name: kubernetes
        tasks_from: kube_apply_manifests.yml

    - name: kube_get_app_url yml
      include_role:
        name: kubernetes
        tasks_from: kube_get_app_url.yml