stages:
  - deploy_locust

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  ANSIBLE_PATH: "provision/ansible"
  TERRAFORM_PATH: "provision/terraform"

deploy_locust:
  stage: deploy_locust
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y wget unzip rsync curl
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  script:
    - echo $ALB_DNS
    - source ./scripts/default_ansible.sh
    - ansible-playbook -i $ANSIBLE_PATH/inventory.ini $ANSIBLE_PATH/deploy_locust.yml -v
    - wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
    - unzip terraform_1.10.5_linux_amd64.zip -d /usr/local/bin/
