stages:
  - provision
  - build
  - deploy
  - cleanup

include:
  - local: 'infrastructure-pipeline.yml'
  - local: 'application-pipeline.yml'

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  TF_VAR_some_variable: "value"  # Example: any Terraform variables you need

terraform_destroy:
  stage: cleanup
  cache:
    key: infrastructure-cache  # Unique key for the cache
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]
  script:
    - cd provision                # Change to provision directory
    - terraform init              # Re-initialize with saved config
    - terraform destroy -auto-approve  # Run destroy command
    - rm infra-status.txt  # Remove the flag file
  dependencies:
    - provision_servers_and_install_k8s_cluster  # Use saved artifacts
  when: manual                    # Make it a manual job
  allow_failure: false            # Fail the pipeline if destroy fails