stages:
  - deploy_prometheus
  - deploy_grafana
  - deploy_elk

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  ANSIBLE_PATH: "provision/ansible"

deploy_prometheus:
  stage: deploy_prometheus
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y unzip curl rsync wget
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  variables:
    KUBECONFIG: "/tmp/kubeconfig"
  script:
    - source ./scripts/ansible_helm_and_kube_dependencies.sh
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace -f provision/helm/prometheus/custom-values.yml
    - helm list --all-namespaces

deploy_grafana:
  stage: deploy_grafana
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y unzip curl rsync wget
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  variables:
    KUBECONFIG: "/tmp/kubeconfig"
  script:
    - source ./scripts/ansible_helm_and_kube_dependencies.sh
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
    - helm upgrade --install grafana grafana/grafana --namespace monitoring -f provision/helm/grafana/custom-values.yml
    - helm list --all-namespaces
    - ANSIBLE_CONFIG=$ANSIBLE_PATH/ansible.cfg ansible-playbook -i $ANSIBLE_PATH/inventory.ini $ANSIBLE_PATH/get_monitoring_resources.yml -vv

deploy_elk:
  stage: deploy_elk
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y unzip curl rsync wget
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  variables:
    KUBECONFIG: "/tmp/kubeconfig"
  script:
    - source ./scripts/ansible_helm_and_kube_dependencies.sh
    - helm repo add elastic https://helm.elastic.co
    - helm repo update
    - helm install elasticsearch elastic/elasticsearch --namespace logging --create-namespace -f provision/helm/elk/elasticsearch/values-elasticsearch.yml
    - ANSIBLE_CONFIG=$ANSIBLE_PATH/ansible.cfg ansible-playbook -i $ANSIBLE_PATH/inventory.ini $ANSIBLE_PATH/get_logging_resources.yml -vv
    - helm install kibana elastic/kibana -n logging -f provision/helm/elk/kibana/values-kibana.yml
    - helm upgrade --install filebeat elastic/filebeat -n logging -f provision/helm/elk/filebeat/values-filebeat.yml
    - helm list --all-namespaces
    - ANSIBLE_CONFIG=$ANSIBLE_PATH/ansible.cfg ansible-playbook -i $ANSIBLE_PATH/inventory.ini $ANSIBLE_PATH/get_monitoring_resources.yml -vv
