stages:
  - provision   # Required for infra jobs
  - build
  - deploy
  - get_node_port
  - terraform_detach
  - terraform_update
  - terraform_reattach
  - get_app_url
  - cleanup

include:
  - local: '.gitlab-ci-infra.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(infra|both)/'
  - local: '.gitlab-ci-app.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(django|both)/'
