stages:
  - provision
  - cleanup

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

provision_servers_and_install_k8s_cluster:
  stage: provision
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  script:
    - echo "Provisioning EC2 instances using Terraform"
    - apt-get update && apt-get install -y wget unzip rsync curl
    - wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
    - unzip terraform_1.10.5_linux_amd64.zip -d /usr/local/bin/
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - cd provision/terraform
    - terraform init
    - terraform apply -auto-approve
    - terraform output -json > output.json
    - python3 create_inv.py
    - terraform output alb_dns_name
    - printf "ALB_DNS=%s" "$(terraform output alb_dns_name)" > .env
    - mv .env ../../
    - cd ../../
    - cd provision
    - aws s3 cp ansible/inventory.ini s3://$AWS_BUCKET_NAME/ansible/inventory.ini
    - aws s3 cp terraform/.terraform.lock.hcl s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl
    - aws s3 cp terraform/terraform.tfstate s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate
    - chmod 755 ansible
    - cd ansible
    - echo "$SSH_PRIVATE_KEY" > ssh_key.pem
    - chmod 600 ssh_key.pem
    - ansible-playbook -i inventory.ini gitlab_provisioning_k8s_cluster.yml
    - cd ../../
  artifacts:
    reports:
      dotenv: .env

terraform_destroy:
  stage: cleanup
  image:
    name: hashicorp/terraform:1.10.5
    entrypoint: [""]
  script:
    - apk update && apk add --no-cache unzip curl
    - apk add --no-cache aws-cli
    - cd provision/terraform
    - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate .
    - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl .
    - terraform init
    - terraform destroy -auto-approve
    - aws s3 rm s3://$AWS_BUCKET_NAME/ansible/inventory.ini
    - aws s3 rm s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate
    - aws s3 rm s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl
  when: manual
