stages:
  - deploy_prometheus
  - deploy_grafana

deploy_prometheus:
  stage: deploy_prometheus
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y unzip curl rsync wget
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  variables:
    KUBECONFIG: "/tmp/kubeconfig"
  script:
    - source ./scripts/ansible_helm_and_kube_dependencies.sh
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace -f ../helm/prometheus/custom-values.yml
    - helm list --all-namespaces
    - ansible-playbook -i inventory.ini get_monitoring_resources.yml -vv

deploy_grafana:
  stage: deploy_grafana
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - apt-get update && apt-get install -y unzip curl rsync wget
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  variables:
    KUBECONFIG: "/tmp/kubeconfig"
  script:
    - source ./scripts/ansible_helm_and_kube_dependencies.sh
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
    - helm upgrade --install grafana grafana/grafana --namespace monitoring --create-namespace -f custom-values.yaml
    - helm list --all-namespaces
    - ansible-playbook -i inventory.ini get_monitoring_resources.yml -vv
