include:
  - local: '.gitlab-ci-infra.yml'
  # - local: '.gitlab-ci-app.yml'

# stages:
#   - triggers

# trigger_a:
#   stage: triggers
#   trigger:
#     include: a/.gitlab-ci.yml
#   rules:
#     - changes:
#         - a/*

# trigger_b:
#   stage: triggers
#   trigger:
#     include: b/.gitlab-ci.yml
#   rules:
#     - changes:
#         - b/*