stages:
  - provision   # Required for infra jobs
  - build
  - deploy
  - load_balancer # If you have a load balancer stage
  - cleanup     # If you have a cleanup stage

include:
  - local: '.gitlab-ci-infra.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(infra|both)/'
  - local: '.gitlab-ci-app.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(django|both)/'