stages:
  - provision
  - cleanup

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  ANSIBLE_PATH: "provision/ansible"
  TERRAFORM_PATH: "provision/terraform"

provision_servers_and_install_k8s_cluster:
  stage: provision
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
    - ansible-galaxy collection install community.general
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  script:
    - echo "Provisioning EC2 instances using Terraform"
    - apt-get update && apt-get install -y wget unzip rsync curl tar
    - wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
    - unzip terraform_1.10.5_linux_amd64.zip -d /usr/local/bin/
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - terraform -chdir=$TERRAFORM_PATH init
    - terraform -chdir=$TERRAFORM_PATH apply -auto-approve
    - aws s3 cp $TERRAFORM_PATH/.terraform.lock.hcl s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl
    - aws s3 cp $TERRAFORM_PATH/terraform.tfstate s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate
    - terraform -chdir=$TERRAFORM_PATH output -json > $TERRAFORM_PATH/output.json
    - python3 $TERRAFORM_PATH/create_inventory_ini.py
    - aws s3 cp $ANSIBLE_PATH/inventory.ini s3://$AWS_BUCKET_NAME/ansible/inventory.ini
    - terraform -chdir=$TERRAFORM_PATH output alb_dns_name
    - printf "ALB_DNS=%s" "$(terraform -chdir=$TERRAFORM_PATH output -raw alb_dns_name)" > .env
    - echo $ALB_DNS
    - chmod 755 $ANSIBLE_PATH
    - echo "$SSH_PRIVATE_KEY" > $ANSIBLE_PATH/ssh_key.pem
    - chmod 600 $ANSIBLE_PATH/ssh_key.pem
    - ANSIBLE_CONFIG=$ANSIBLE_PATH/ansible.cfg ansible-playbook -i $ANSIBLE_PATH/inventory.ini $ANSIBLE_PATH/gitlab_provisioning_k8s_cluster.yml -vv
  artifacts:
    reports:
      dotenv: .env

terraform_destroy:
  stage: cleanup
  image:
    name: hashicorp/terraform:1.10.5
    entrypoint: [""]
  script:
    - apk update && apk add --no-cache unzip curl
    - apk add --no-cache aws-cli
    - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate $TERRAFORM_PATH/
    - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl $TERRAFORM_PATH/
    - terraform -chdir=$TERRAFORM_PATH init
    - terraform -chdir=$TERRAFORM_PATH destroy -auto-approve
    - aws s3 rm s3://$AWS_BUCKET_NAME/ansible/inventory.ini
    - aws s3 rm s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate
    - aws s3 rm s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl
  when: manual
