include:
  - local: 'infrastructure-pipeline.yml'
  - local: 'application-pipeline.yml'

terraform_destroy:
  stage: cleanup
  script:
    - cd provision                # Change to provision directory
    - terraform init              # Re-initialize with saved config
    - terraform destroy -auto-approve  # Run destroy command
    - rm infra-status.txt  # Remove the flag file
  dependencies:
    - provision_servers_and_install_k8s_cluster  # Use saved artifacts
  when: manual                    # Make it a manual job
  allow_failure: false            # Fail the pipeline if destroy fails