stages:
  - provision   # Required for infra jobs
  - build
  - deploy_and_get_app_url
  - cleanup

include:
  - local: '.gitlab-ci-infra.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(infra|both)/'
  - local: '.gitlab-ci-app.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(django|both)/'
