include:
  - local: '.gitlab-ci-infra.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /infra/'
  - local: '.gitlab-ci-app.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /django/'

# stages:
#   - triggers

# trigger_a:
#   stage: triggers
#   trigger:
#     include: a/.gitlab-ci.yml
#   rules:
#     - changes:
#         - a/*

# trigger_b:
#   stage: triggers
#   trigger:
#     include: b/.gitlab-ci.yml
#   rules:
#     - changes:
#         - b/*