include:
  - local: '.gitlab-ci-infra.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(infra|all)/'
  - local: '.gitlab-ci-app.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(django|all)/'
  - local: '.gitlab-ci-monitoring.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(locust|all)/'
  - local: '.gitlab-ci-locust.yml'
    rules:
      - if: '$CI_COMMIT_MESSAGE =~ /(monitoring|all)/'

stages:
  - provision   # Required for infra jobs
  - build
  - deploy_and_get_app_url
  - deploy_prometheus
  - deploy_grafana
  - deploy_elk
  - deploy_locust
  - cleanup
