stages:
  - locust_deploy

.default_terraform: &default_terraform
  - cd provision/terraform
  - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/terraform.tfstate .
  - aws s3 cp s3://$AWS_BUCKET_NAME/terraform/.terraform.lock.hcl .
  - terraform init

.default_ansible: &default_ansible
  - apt-get update && apt-get install -y unzip curl
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - aws s3 cp s3://$AWS_BUCKET_NAME/ansible/inventory.ini provision/ansible/inventory.ini
  - chmod 755 provision/ansible
  - cd provision/ansible
  - echo "$SSH_PRIVATE_KEY" > ssh_key.pem
  - chmod 600 ssh_key.pem

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

locust_deploy:
  stage: locust_deploy
  before_script:
    - ansible-galaxy collection install kubernetes.core
    - ansible-galaxy collection install community.kubernetes
  image:
    name: willhallonline/ansible:2.18.2-ubuntu-24.04
    entrypoint: [""]
  script:
    - echo $ALB_DNS
    - *default_ansible
    - ansible-playbook -i inventory.ini deploy_locust.yml -v
    - apt-get update && apt-get install -y wget unzip rsync curl
    - wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
    - unzip terraform_1.10.5_linux_amd64.zip -d /usr/local/bin/
