apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-config
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    import os

    class WebsiteUser(HttpUser):
        wait_time = between(1, 3)
        host = os.getenv("LOCUST_TARGET_HOST")
        @task
        def homepage(self):
            self.client.get("/")
