---
- name: Ensure the project directory exists
  ansible.builtin.file:
    path: "/code"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy pyproject.toml
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname | dirname }}/djangoarticleapp/"
    dest: /code/pyproject.toml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Copy poetry.lock
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname | dirname }}/djangoarticleapp/"
    dest: /code/poetry.lock
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Copy README.md files
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname | dirname }}/djangoarticleapp/"
    dest: /code/README.md
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Copy project files to the instance
  synchronize:
    src: "{{ playbook_dir | dirname | dirname }}/djangoarticleapp/"
    dest: /code
    rsync_opts:
      - "--exclude=.venv"
      - "--exclude=.vscode"

- name: Copy start-django.sh to the server
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname | dirname }}/djangoarticleapp/start-django.sh"
    dest: /code/start-django.sh
    mode: '0755'  # This ensures the file is executable
