---
- name: Generate kubeadm join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_output
  changed_when: false

- name: Fetch the kubeadm join command from the master node
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ join_command_output.stdout }}"

- name: Show the join command
  ansible.builtin.debug:
    msg: "{{ kubeadm_join_command }}"
