---
- name: Dump all variables for the host separately
  ansible.builtin.debug:
    msg: "{{ hostvars[item].locust_hostname }}"
  loop: "{{ groups['locust'] }}"

- name: Label all locust nodes
  ansible.builtin.command:
    kubectl label node {{ hostvars[item].locust_hostname }} node-type=locust --overwrite
  loop: "{{ groups['locust'] }}"
  register: label_output
  changed_when: label_output.rc != 0
