---
- name: Install required dependencies
  ansible.builtin.command: sudo yum -y install git curl unzip bash-completion runc containerd
  register: dependencies
  changed_when: dependencies.rc != 0

- name: Start containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started

- name: Enable containerd to start on boot
  ansible.builtin.systemd:
    name: containerd
    enabled: true
