server:
  service:
    type: NodePort
    port: 80
    nodePort: 30013
    targetPort: 9090
  persistentVolume:
    enabled: false
    emptyDir: {}
alertmanager:
  persistence:
    enabled: false
    emptyDir: {}
pushgateway:
  persistence:
    enabled: false
    emptyDir: {}
# Configure NodeExporter as headless to be able to srape data from all nodes
prometheus-node-exporter:
  enabled: true
  hostNetwork: false
  service:
    type: ClusterIP
    clusterIP: "None"
