- name: Get elasticsearch secret info
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    namespace: logging
    name: elasticsearch-master-credentials
  register: elastic_secret_info

- name: Debug - show the elastic_secret_info
  ansible.builtin.debug:
    msg: "Elasticsearch password is: {{ elastic_secret_info }}"

- name: Debug - show the elastic_secret_info.resources
  ansible.builtin.debug:
    msg: "Elasticsearch password is: {{ elastic_secret_info.resources }}"

- name: Debug - show the elastic_secret_info.resources[0]
  ansible.builtin.debug:
    msg: "Elasticsearch password is: {{ elastic_secret_info.resources[0] }}"

- name: Debug - show the elastic_secret_info.resources[0].data.password
  ansible.builtin.debug:
    msg: "Elasticsearch password is: {{ elastic_secret_info.resources[0].data.password }}"

- name: Set elasticsearch password fact
  ansible.builtin.set_fact:
    elastic_password: "{{ elastic_secret_info.resources[0].data.password | b64decode }}"

- name: Debug - show the Elasticsearch password
  ansible.builtin.debug:
    msg: "Elasticsearch password is: {{ elastic_password }}"
