apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "djangoarticleapp.fullname" .) }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.targetPort }}
      nodePort: {{ .Values.django.service.nodePort }}
  selector:
    app: {{ include "djangoarticleapp.name" . }}
