apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DATABASE_URL: {{ .Values.django.config.databaseUrl | quote }}
  # POSTGRES_DB: {{ .Values.django.config.postgresDb | quote }}
  # POSTGRES_USER: {{ .Values.django.config.postgresUser | quote }}
  # POSTGRES_PASSWORD: {{ .Values.django.config.postgresPassword | quote }}
