apiVersion: v1
kind: Secret        # use a Secret not a ConfigMap for creds
metadata:
  name: postgres-init
type: Opaque
stringData:
  POSTGRES_DB:       {{ .Values.postgres.database }}
  POSTGRES_USER:     {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
