---
- name: Checks
  shell: |
    kubectl get svc db
    kubectl get pods

- name: Get the first pod name
  shell: |
    kubectl get pods -o jsonpath='{.items[0].metadata.name}'
  register: pod_name

- name: Debug the first pod name
  debug:
    var: pod_name.stdout

- name: Fetch logs of the first pod
  shell: |
    kubectl logs {{ pod_name.stdout }}
  register: pod_logs

- name: Display the logs
  debug:
    var: pod_logs.stdout