---
- name: Print kubeadm_join_command
  debug:
    msg: "Print kubeadm_join_command {{ hostvars[groups['master'][0]].kubeadm_join_command }}"

- name: Fetch the kubeadm join command from the master node
  set_fact:
    kubeadm_join_command: "{{ hostvars[groups['master'][0]].kubeadm_join_command }}"

- name: Join the worker node to the master
  ansible.builtin.shell:
    cmd: "{{ kubeadm_join_command }}"
    creates: /etc/kubernetes/kubelet.conf
  environment:
    KUBELET_EXTRA_ARGS: "--node-labels=role=worker"
  register: join_status

- name: Check if node joined successfully
  ansible.builtin.debug:
    msg: "Node successfully joined the Kubernetes cluster"
  when: join_status.rc == 0