- name: Get pods in the monitoring namespace
  ansible.builtin.command: kubectl get pods -n monitoring
  register: pods_output
  changed_when: false

- name: Display pods output
  ansible.builtin.debug:
    msg: "{{ pods_output.stdout }}"

- name: Get services in the monitoring namespace
  ansible.builtin.command: kubectl get svc -n monitoring
  register: svc_output
  changed_when: false

- name: Show Prometheus access URL using NodePort
  ansible.builtin.debug:
    msg: "Prometheus is accessible at http://{{ hostvars[groups['master'][0]].ansible_host }}:30013"

- name: Show Grafana access URL using NodePort
  ansible.builtin.debug:
    msg: "Prometheus is accessible at http://{{ hostvars[groups['locust'][0]].ansible_host }}:32013"
