---
- name: Get Django service NodePort
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    kubectl get svc djangoarticleapp-service -o jsonpath='{.spec.ports[0].nodePort}'
  register: django_nodeport
  changed_when: false

- name: Print Node port
  ansible.builtin.debug:
    var: django_nodeport.stdout_lines

# This needs CI_PROJECT_DIR to be set because gitlab reads files from that
- name: Write NodePort value to .env file
  ansible.builtin.copy:
    content: "NODE_PORT={{ django_nodeport.stdout }}"
    dest: "{{ lookup('env', 'CI_PROJECT_DIR') }}/.env"
  delegate_to: localhost
  mode: '0644'
