---
- name: Dump all variables for the host separately
  debug:
    msg: "{{ hostvars[item].worker_hostname}}"
  loop: "{{ groups['workers'] }}"

- name: Label all worker nodes
  command: kubectl label node {{ hostvars[item].worker_hostname }} node-type=worker --overwrite
  loop: "{{ groups['workers'] }}"