---
- name: Deploy Django application via Helm (unified release)
  kubernetes.core.helm:
    name: djangoarticleapp
    chart_ref: "{{ playbook_dir }}/../helm/djangoarticleapp"
    release_namespace: default
    kubeconfig: /tmp/kubeconfig
    values:
      createGitlabRegistrySecret: true
      docker_config:
        auths:
          registry.gitlab.com:
            username: "{{ lookup('env', 'GITLAB_USERNAME') }}"
            password: "{{ lookup('env', 'GITLAB_REGISTRY_TOKEN') }}"
            email: "{{ lookup('env', 'GITLAB_EMAIL') }}"
            auth: "{{ (lookup('env', 'GITLAB_USERNAME') + ':' + lookup('env', 'GITLAB_REGISTRY_TOKEN')) | b64encode }}"
      django:
        image:
          repository: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"
          tag: "{{ lookup('env', 'CI_COMMIT_SHA') | default('latest') }}"
  delegate_to: localhost

- name: Check Helm status of django-release
  ansible.builtin.command: helm status djangoarticleapp --kubeconfig=/tmp/kubeconfig
  delegate_to: localhost
  register: helm_status_output
  changed_when: false

- name: Show Helm status output
  ansible.builtin.debug:
    msg: "{{ helm_status_output.stdout_lines }}"
