---
- name: Get Django service NodePort
  shell: |
    kubectl get svc djangoarticleapp-service -o jsonpath='{.spec.ports[0].nodePort}'
  register: django_nodeport

- name: Print application URL
  debug:
    msg: "http://{{ groups['workers'][0] }}:{{ django_nodeport.stdout }}"