---
- name: Get Django service NodePort
  shell: |
    kubectl get svc djangoarticleapp-service -o jsonpath='{.spec.ports[0].nodePort}'
  register: django_nodeport

- name: Get Django service External IP
  shell: kubectl get svc djangoarticleapp-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: django_external_ip

- name: Update ALB configuration with new node_port
  delegate_to: localhost
  run_once: true
  command: terraform apply -var "node_port={{ django_nodeport.stdout | int }}" -auto-approve
  args:
    chdir: "{{ playbook_dir }}/../terraform"

- name: Print application URL - Django service External IP
  debug:
    msg: "http://{{ django_external_ip.stdout }}:{{ django_nodeport.stdout }}"

- name: Print application URL - worker IP
  debug:
    msg: "http://{{ groups['workers'][0].ansible_host }}:{{ django_nodeport.stdout }}"

