---
- name: Check if folder exists
  ansible.builtin.stat:
    path: $HOME/.kube
  register: folder_check

- name: Set up kubeconfig for kubectl (admin access) on master node -  Execute command if folder does not exist
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  when: not folder_check.stat.exists
  register: kubeconfig
  changed_when: false
