---
- name: Dump all variables for the host separately
  ansible.builtin.debug:
    msg: "{{ hostvars[item].worker_hostname }}"
  loop: "{{ groups['workers'] }}"

- name: Label all worker nodes
  ansible.builtin.command:
    kubectl label node {{ hostvars[item].worker_hostname }} node-type=worker --overwrite
  loop: "{{ groups['workers'] }}"
  register: label_output
  changed_when: label_output.rc != 0
