---
- name: Fetch the kubeadm join command
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ hostvars[groups['master'][0]].kubeadm_join_command }}"

- name: Fetch the kubeadm certificate
  ansible.builtin.set_fact:
    kubeadm_certificate_key_clean: "{{ hostvars[groups['master'][0]].kubeadm_certificate_key_clean }}"

- name: Debug output
  ansible.builtin.debug:
    var: "{{ hostvars[groups['master'][0]].kubeadm_certificate_key_clean }}"

- name: Debug output
  ansible.builtin.debug:
    var: kubeadm_certificate_key_clean

- name: Join the other master nodes to the main master node
  ansible.builtin.command:
    cmd: "{{ kubeadm_join_command }} --control-plane --certificate-key {{ kubeadm_certificate_key_clean }} --ignore-preflight-errors=all --v=7"
    creates: /etc/kubernetes/kubelet.conf
  register: join_status
  changed_when: join_status.rc != 0

- name: Check if node joined successfully
  ansible.builtin.debug:
    msg: "Node successfully joined the Kubernetes cluster"
  when: join_status.rc == 0
