---
- name: Checks
  ansible.builtin.shell: |
    kubectl get svc db
    kubectl get pods
  register: checks
  changed_when: false

- name: Get the first pod name
  ansible.builtin.shell: |
    kubectl get pods -o jsonpath='{.items[0].metadata.name}'
  register: pod_name
  changed_when: false

- name: Debug the first pod name
  ansible.builtin.debug:
    var: pod_name.stdout_lines

- name: Fetch logs of the first pod
  ansible.builtin.shell: |
    kubectl logs {{ pod_name.stdout_lines }}
  register: pod_logs
  changed_when: false

- name: Display the logs
  ansible.builtin.debug:
    var: pod_logs.stdout_lines
