---
- name: Add Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.26/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.26/rpm/repodata/repomd.xml.key
    owner: root
    group: root
    mode: '0644'

# Amazon Linux 2
- name: Install required dependencies
  ansible.builtin.shell: |
    sudo yum install -y kubelet kubeadm kubectl
  register: my_output
  changed_when: false

- name: Copy Kubernetes app provisioning files
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname }}/helm"
    dest: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# - name: Copy Kubernetes app provisioning files
#   ansible.builtin.copy:
#     src: "{{ playbook_dir | dirname }}/k8s-manifests-app"
#     dest: /home/ec2-user
#     owner: ec2-user
#     group: ec2-user
#     mode: '0755'

- name: Copy Kubernetes locust manifests files
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname }}/k8s-manifests-locust"
    dest: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# Amazon Linux 2023
# - name: Install kubeadm, kubelet, and kubectl
#   dnf:
#     name:
#       - kubelet
#       - kubeadm
#       - kubectl
#     state: present
#   notify: Restart kubelet
