---
- name: Save hostname result
  ansible.builtin.command: hostname
  register: hostname_command
  changed_when: false

- name: Save hostname result
  ansible.builtin.set_fact:
    worker_hostname: >-
      "{{ hostname_command.stdout }}"
