---
- name: Checks
  ansible.builtin.shell: |
    kubectl get svc db
    kubectl get pods
  register: checks
  changed_when: checks.rc != 0

- name: Get the first pod name
  ansible.builtin.shell: |
    kubectl get pods -o jsonpath='{.items[0].metadata.name}'
  register: pod_name
  changed_when: pod_name.rc != 0

- name: Debug the first pod name
  ansible.builtin.debug:
    var: pod_name.stdout

- name: Fetch logs of the first pod
  ansible.builtin.shell: |
    kubectl logs {{ pod_name.stdout }}
  register: pod_logs
  changed_when: pod_logs.rc != 0

- name: Display the logs
  ansible.builtin.debug:
    var: pod_logs.stdout
