# Generated by Django 5.1.5 on 2025-01-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_alter_article_content_alter_article_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
