apiVersion: v1
kind: Service
metadata:
  name: djangoarticleapp-service
spec:
  type: NodePort
  ports:
    - port: 8000          # Port exposed internally in the cluster
      targetPort: 8000    # Port the app is listening on in the pod
      nodePort: 31131
  selector:
    app: djangoarticleapp  # Matches the labels of your pods
