---
- name: Create the file for Forwarding IPv4 and iptables modules
  become: true
  ansible.builtin.file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
    mode: '0644'

- name: Configure Forwarding IPv4 and letting iptables see bridged traffic
  become: true
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      overlay
      br_netfilter

- name: Set modprobe overlay
  become: true
  community.general.modprobe:
    name: overlay
    state: present

- name: Verify that the overlay modules are loaded
  ansible.builtin.shell: |
    set -o pipefail
    lsmod | grep overlay
  register: overlay
  changed_when: false

- name: Debug overlay
  ansible.builtin.debug:
    msg: "{{ overlay.stdout_lines }}"

- name: Modprobe br_netfilter
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present
  changed_when: false

- name: Verify that the br_netfilter modules are loaded
  ansible.builtin.shell: |
    set -o pipefail
    lsmod | grep br_netfilter
  register: br_netfilter
  changed_when: false

- name: Debug br_netfilter
  ansible.builtin.debug:
    msg: "{{ br_netfilter.stdout_lines }}"

- name: Configure sysctl for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    mode: '0644'
  notify: Reload sysctl

- name: Verify that the net.bridge.bridge-nf-call-iptables, net.bridge.bridge-nf-call-ip6tables, net.ipv4.ip_forward system variables are set to 1
  ansible.builtin.shell: |
    sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
  register: bridge_net
  changed_when: false

- name: Debug bridge_net
  ansible.builtin.debug:
    msg: "{{ bridge_net.stdout_lines }}"

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  changed_when: false

- name: Install pre-requisites for python
  ansible.builtin.pip:
    name:
      - openshift
      - pyyaml
      - kubernetes

# - name: Ensure SELinux is disabled
#   ansible.builtin.selinux:
#     state: disabled

# # - name: Disable SELinux
# #   command: setenforce 0
# #   when: ansible_selinux.status == "enabled"
# #   failed_when: false

# - name: Ensure SELinux is set to permissive in config file
#   lineinfile:
#     path: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: 'SELINUX=permissive'
