---
- name: Install pyenv repository
  ansible.builtin.git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "/home/{{ ansible_user }}/.pyenv"  # Use the correct user's home directory
    version: master
  register: pyenv_install_output
  become: true
  become_user: "{{ ansible_user }}" 

- debug:
    msg: "Git output: {{ pyenv_install_output }}"

- name: Debug python_version
  ansible.builtin.debug:
    var: python_version

- name: Debug ansible_user
  ansible.builtin.debug:
    var: ansible_user

- name: Add pyenv to shell configuration
  ansible.builtin.shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ ansible_user }}"  # Modify the user's bashrc
  notify: Restart shell

- name: Ensure pyenv is available
  ansible.builtin.shell: |
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    pyenv --version
  register: pyenv_check
  become: true
  become_user: "{{ ansible_user }}"  # Modify the user's bashrc

- debug:
    msg: "Pyenv version: {{ pyenv_check.stdout }}"