---
# - name: Debug home directory
#   debug:
#     msg: "Home directory is: {{ ansible_env.HOME }}"

- name: Install required packages for building Python
  yum:
  dnf:
    name: 
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - libffi-devel
      - git
      - make
    state: present
