---
- name: Install Poetry
  shell: /home/ec2-user/.pyenv/versions/3.13.0/bin/python3.13 -m pip install poetry

- name: Add Poetry to PATH (for ec2-user)
  lineinfile:
    path: "/home/ec2-user/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: yes
  notify:
    - Restart shell