---
- name: Install Nginx using amazon-linux-extras
  ansible.builtin.shell: |
      sudo yum -y clean metadata
      sudo amazon-linux-extras enable nginx1
      sudo yum -y clean metadata
      sudo yum -y install nginx
      sudo yum -y install nginx-mod-stream
  register: nginx_install
  changed_when: false

- name: Create directory for stream configurations
  ansible.builtin.file:
    path: /etc/nginx/stream-conf.d
    state: directory
    mode: '0755'

- name: Wait for stream configuration directory to exist
  ansible.builtin.wait_for:
    path: /etc/nginx/stream-conf.d
    state: present
    timeout: 30

- name: Deploy Nginx stream configuration for kube-apiserver load balancing
  ansible.builtin.template:
    src: templates/kube-apiserver.conf.j2
    dest: /etc/nginx/stream-conf.d/kube-apiserver.conf
    mode: '0644'
  notify: Reload Nginx

- name: Ensure top-level stream block exists in nginx.conf
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    marker: "# {mark} ANSIBLE STREAM BLOCK"
    block: |
      stream {
          include /etc/nginx/stream-conf.d/*.conf;
      }
  notify: Reload Nginx

# - name: Reload Nginx
#   service:
#     name: nginx
#     state: reloaded
