apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: your-django-image:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: your_db_name
        - name: POSTGRES_USER
          value: your_db_user
        - name: POSTGRES_PASSWORD
          value: your_db_password
        - name: DATABASE_URL
          value: postgres://your_db_user:your_db_password@postgres:5432/your_db_name
